// Do not edit!
// File generated by org.apache.zookeeper.version.util.VerGen.
package org.apache.zookeeper.version;

public interface Info {
    public static final int MAJOR=3;
    public static final int MINOR=0;
    public static final int MICRO=1;
    public static final int REVISION=1;
    public static final String BUILD_DATE="2023-04-06";
}
